apiservices/config/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('panel/', admin.site.urls),
    path('',include('trip.urls')),
    path('account/',include('account.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apiservices/trip/urls.py
from django.urls import path
from .views import CategoryList,FlightListView,FlightDetailview,AuthorList

app_name = "trip"
urlpatterns = [
    path('',FlightListView.as_view() ,name="home"),
    path('page/<int:page>',FlightListView.as_view() ,name="home"),
    path('trip/<slug:slug>',FlightDetailview.as_view(),name='detail'),
    path('category/<slug:slug>',CategoryList.as_view(),name='category'),
    path('author/<slug:username>',AuthorList.as_view(),name='author') 
]

apiservices/trip/models.py
from django.db import models
from account.models import User
from django.urls import reverse
from django.utils.html import format_html
from django.utils import timezone
from extensions.utils import jalali_converter

#flight manager
class FlightManager(models.Manager):
    def published(self):
        return self.filter(status = "p")
    
#category manager
class CategoryManager(models.Manager):
    def active(self):
        return self.filter(status = True)

#  data models .
class Category(models.Model):
    title= models.CharField(max_length = 200,verbose_name="عنوان دسته بندی")
    slug = models.SlugField(max_length = 200,verbose_name=" آدرس دسته بندی ها")
    status= models.BooleanField(default = True,verbose_name="وضعیت پرواز: ")
    position = models.IntegerField(verbose_name = "پوزیشن")

    class Meta:
       verbose_name = "دسته بندی "
       verbose_name_plural = "دسته بندی ها"
       ordering = ["position"]
    def __str__(self):
       return(self.title)
    objects = CategoryManager()

class Hadis(models.Model):
    sentence = models.TextField(verbose_name = "احادیث")
    created = models.DateTimeField(auto_now_add= True,verbose_name = "آخرین بروز رسانی")

    def __str__(self):
        return (self.sentence)
    class Meta:
        verbose_name = "حدیث"
        verbose_name_plural = "احادیث"
        ordering = ["-created"]
    def jcreated(self):
        return jalali_converter(self.created)
    jcreated.short_description= "آخرین بروزرسانی"
    
class Flight(models.Model):
    ft_choices = {
       'EC' : 'اکونومی',
       'BS' : 'بیزینس',
    }
    st_choices = {
        'DO' : 'داخلی',
        'IN' : 'خارجی',
    }
    STATUS_CHOISES={
        'p':'پرواز',
        'd':'کنسل'
    }
    flight_type = models.CharField(max_length = 2,choices = ft_choices,default = "اکونومی",verbose_name="نوع پرواز")
    company = models.CharField(max_length = 100,verbose_name="شرکت هواپیمایی")
    author = models.ForeignKey(User,on_delete=models.SET_NULL,null=True,verbose_name="نویسنده",related_name = "flights")
    slug = models.SlugField(max_length = 200, unique = True,verbose_name="شماره پرواز") #fly no
    category = models.ManyToManyField(Category,verbose_name="دسته بندی",related_name="trips")
    source = models.CharField(max_length = 100,verbose_name="مبدا")
    destination = models.CharField(max_length = 100,verbose_name="مقصد")
    date = models.DateTimeField(verbose_name="تاریخ پرواز")
    fly_time = models.TimeField(verbose_name="ساعت پرواز")
    landing_time = models.TimeField(verbose_name="ساعت فرود")
    price = models.IntegerField(verbose_name="قیمت")
    terminal = models.CharField(null=True,max_length = 100,verbose_name="ترمینال")
    rate_class = models.CharField(max_length = 100,null=True,verbose_name="کلاس پرواز")
    cargo = models.IntegerField(verbose_name="بار مجاز",null=True) #bar mojaz
    airplane_model = models.CharField(null=True,max_length = 100,verbose_name="مدل هواپیما")
    thumbnail = models.ImageField(upload_to ="images")
    service_type = models.CharField(max_length = 2, choices = st_choices,default = "داخلی" ,verbose_name="مسیر پرواز")
    updated = models.DateTimeField(auto_now_add= True,null=True)
    status = models.CharField(max_length = 1,choices = STATUS_CHOISES,default = "پرواز",verbose_name= "وضعیت")
    # hadis = models.ForeignKey("Hadis", verbose_name="حدیث", on_delete=models.CASCADE)

    def __str__(self):
        return(self.source + " ----> " +self.destination)
    class Meta:
        verbose_name = "پرواز "
        verbose_name_plural = "پروازها"
        ordering = ["-updated"]

    def jdate(self):
        return jalali_converter(self.date)
    jdate.short_description="تاریخ پرواز"
    
    def jupdated(self):
        return jalali_converter(self.updated)
    
    def get_absolute_url(self):
        return reverse("account:home")
    
    
    def category_published(self):
        return self.category.filter(status = True)
    
    def thumbnail_tag(self):
        return format_html("<img width=50 height=50 style= 'border-radius:50px' src = '{}'>".format(self.thumbnail.url))
    thumbnail_tag.short_description="لوگو "

    def category_to_str(self):
        return " , ".join([category.title for category in self.category_published()])
    category_to_str.short_description=" دسته بندی"
    
    objects = FlightManager()
    
    
    

apiservices/trip/views.py
from typing import Any
from django.db.models.base import Model as Model
from account.models import User
from django.views.generic import ListView,DetailView
from django.shortcuts import render,get_object_or_404
from .models import Flight,Hadis,Category


# Create your views here.
# def home(request,page=1):
#     flight_list = Flight.objects.published()
#     paginator = Paginator(flight_list, 4)
#     flights = paginator.get_page(page)
#     context={
#         'flights' : flights,
#         'hadises' : Hadis.objects.all()[:1],
#         'category': Category.objects.filter(status = True),
#     }
#     return render(request,'trip/home.html',context)


# def detail(request,slug):
#     context={
#         # 'flight' : Flight.objects.get(slug=slug)
#         'flight' : get_object_or_404(Flight.objects.published(),slug=slug)
        
#     }
  
#     return render(request,'trip/detail.html',context)


class HadisListView(ListView):
     model = Hadis
     
class FlightListView(ListView): 
    queryset = Flight.objects.published()
    paginate_by = 4

class FlightDetailview(DetailView):
    def get_object(self):
        slug = self.kwargs.get('slug')
        return get_object_or_404(Flight.objects.published(),slug=slug)

class CategoryList(ListView):
    paginate_by = 4
    template_name= 'trip/category_list.html'
    def get_queryset(self): 
        global category
        slug = self.kwargs.get('slug')
        category = get_object_or_404(Category.objects.active(),slug = slug)
        return category.trips.published()
    
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context["category"] = category
        return context

class AuthorList(ListView):
       paginate_by = 4
       template_name= 'trip/author_list.html'
       def get_queryset(self): 
            global author
            useername = self.kwargs.get('useername')
            author = get_object_or_404(User,slug = useername)
            return author.trips.published()
    
       def get_context_data(self, **kwargs):
            # Call the base implementation first to get a context
            context = super().get_context_data(**kwargs)
            # Add in a QuerySet of all the books
            context["author"] = author
            return context

apiservices/templates/trip/author_list.html
<p>
    {{author.get_full_name}}
</p>

apiservices/templates/trip/base.html
{%load static%}
{% load base_tags %}
<!DOCTYPE html>
<html lang="en" >
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>.:Flight List:. {% block title%}{%endblock%} </title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Option 1: Include in HTML -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'trip/css/styles.css'%}" rel="stylesheet" />
        <link href="{% static 'trip/css/rtl.css'%}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-dark" id="mainNav">
            <div class="container px-4 px-lg-5">
              
                <a class="navbar-brand" href="{% url 'trip:home' %}">{% title %}</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    منو
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'trip:home' %}">خانه</a></li>
                       {%for cat in object_list%}
                       <li class="nav-item "><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'trip:category' cat.slug %}">{{cat.title}}</a></li>
                        
                       {%endfor%}
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        <!-- <header class="masthead" style="background-image: url('assets/img/home-bg.jpg')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            
                            <h1>وبلاگ API</h1>
                            <span class="subheading">نمایش تمامیه سفرها</span>
                        </div>
                    </div>
                </div>
            </div>
        </header> -->
        <!-- Main Content-->
    {% block main %}
    {% endblock %}
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; &#x46; . &#x4b;</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

apiservices/templates/trip/category_list.html
{%extends 'trip/base.html'%}
{% load static%}
{% block main %}
<div class="container px-4 px-lg-5 ">
    <div class="row gx-4 gx-lg-5 justify-content-center mt-5 pt-5">
        {%for hadis in hadises%}
        <div class="shadow p-3 mb-4 bg-body-tertiary rounded row gx-4 gx-lg-5 justify-content-center ">{{hadis.sentence}}</div>
        {%endfor%}
        
        <!-- col-md-1 col-lg-4 col-xl-4 d-inline-flex w-100  -->
        <div class="row row-cols-2 row-cols-md-3 row-cols-lg-4 g-1 w-100 d-inline-flex">
            
            <!-- <div class="card-columns mh-100 " > -->
        <!-- Post preview-->
        <!-- <div class="shadow-lg p-3 mb-5 bg-body-tertiary rounded row gx-4 gx-lg-5 justify-content-center "> -->
            {% for flight in category.trips.all %}
                <div class = "m-0">

                    <div class=" card border-dark mb-3 rounded-3 shadow" >
                        <div class="card text-center d-inline">
                            {% for cat in flight.category_published.all %}

                            {% comment %} <a class="btn btn-primary m-1" href="#" role="button" style="width: 20px;height: 5px ;font-size: 12px;" >{{cat.title}}</a> {% endcomment %}
                            <a href="#" class="btn btn-outline-info rounded-pill p-2 m-1"style= "font-size:10px">{{cat.title}}</a>
                                {% comment %} <span class="badge badge-warning">{{cat.title}}</span> {% endcomment %}
                                                       
                            {%endfor%}
                            {% comment %}                             
                            {%if flight.flight_type == "EC"%}
                            اکونومی
                            {% elif flight.flight_type == "BS"%}
                            بیزینس
                            {%endif%} {% endcomment %}
                            
                        </div>
                        <div class="card-body pb-2">
                            <h5 class="card-title text-center"> {{flight.source}} <i class='far fas fa-arrow-left' style="font-size:12px;color:red" >	</i>  {{flight.destination}} </h5>
                            <div class = "d-inline-flex mt-1 pt-1">

                                <img src= '{{flight.thumbnail.url}}'class="img-fluid rounded" alt="{{flight.slug}}"style="width: 50px;height: 50px">
                                <small class = "m-3"> {{flight.company}}</small>
                            </div>
                            <p class="card-text mt-1 pt-1 mb-1 pb-1"style= "font-size:14px">تاریخ پرواز: {{flight.jdate}}</p>
                            <p class="card-text mt-1 pt-1 mb-2 pb-1"style= "font-size:14px">ساعت پرواز: {{flight.fly_time}}</p>
                            <a href="{% url 'trip:detail' flight.slug%}" class="btn btn-outline-dark rounded-pill w-100 p-1 "style="height: 25px;font-size:12px">جزییات</a>
                            
                        </div>
                        <div class="card-footer text-muted text-center pt-1" style= "font-size:12px">
                            {{flight.jupdated}}
                        </div>
                    </div>
                    
                </div>
                {%endfor%}
            </div>
            
        
        



            <!-- <div class="post-preview">
                {%for trip in trips%}
                <a href="post.html">
                    <h class="post-title">{{trip.title}}</h2>
                    <h5 class="post-subtitle">{{trip.explanation}}</h5>
                </a>
                <p class="post-meta">
                    Posted by
                    <a href="#!">{{trip.copyright}}</a>
                    on {{trip.date}}
                </p>
                <hr class="my-4" />
                    {%endfor%}
            </div> -->
            <!-- </div> -->
            <!-- Divider-->
            <!-- Post preview-->
           
            <!-- Divider-->
            <!-- <hr class="my-4" /> -->
            <!-- Pager-->
            <div class="d-flex justify-content-end mb-4 pager-bottom "><a class="btn btn-outline-success text-uppercase rounded-pill" href="#!">  لیست سفرهای قدیمی <i class='fas fa-chevron-left' style='font-size:11px'></i></a></div>
        </div>
    </div>
</div>
{%endblock%}

apiservices/templates/trip/flight_detail.html
{%extends 'trip/base.html'%}
{% block title%} | {{flight.slug}} {%endblock%}
{% block main %}




<div class="container px-4 px-lg-5 ">
    <div class="row gx-4 gx-lg-5 justify-content-center mt-5 pt-5">
        {%for hadis in hadises%}
        <div class="shadow p-3 mb-4 bg-body-tertiary rounded row gx-4 gx-lg-5 justify-content-center ">{{hadis.sentence}}</div>
        {%endfor%}
        
        <!-- col-md-1 col-lg-4 col-xl-4 d-inline-flex w-100  -->
        <!-- <div class="row row-cols-2 row-cols-md-3 row-cols-lg-4 g-1 w-100 "> -->
            
            <!-- <div class="card-columns mh-100 " > -->
        <!-- Post preview-->
        <!-- <div class="shadow-lg p-3 mb-5 bg-body-tertiary rounded row gx-4 gx-lg-5 justify-content-center "> -->
            
                <div class = "m-0">

                    <div class=" card border-dark mb-3 rounded-3 shadow w-70" >
                        

                            <div class="card text-center bg-light d-inline-flex">
                                
                                {%if flight.flight_type == "EC"%}
                                اکونومی
                                {% elif flight.flight_type == "BS"%}
                                بیزینس
                                {%endif%}
                                
                                
                            </div>
                        
                        <div class="card-body ml-2">
                        
                            <h5 class="card-title text-center"> {{object.source}} ==>> {{flight.destination}} </h5>
                            <div class = "d-inline-flex mt-1 pt-1">

                                <img src= '{{flight.thumbnail.url}}'class="img-fluid rounded" alt="{{flight.slug}}"style="width: 50px;height: 50px">
                                <small class = "m-3"> {{flight.company}}</small>
                            </div>
                            <p class="card-text mt-1 pt-1 mb-1 pb-1">تاریخ پرواز: {{flight.jdate}}</p>
                            <p class="card-text mt-1 pt-1 mb-1 pb-1">شماره پرواز: {{flight.slug}}</p>
                            <p class="card-text mt-1 pt-1 mb-2 pb-1">ساعت پرواز: {{flight.fly_time}}</p>
                            <p class="card-text mt-1 pt-1 mb-2 pb-1">ساعت فرود: {{flight.landing_time}}</p>
                            <p class="card-text mt-1 pt-1 mb-2 pb-1">قیمت پرواز: {{flight.price}} تومان</p>
                            <p class="card-text mt-1 pt-1 mb-2 pb-1">بار مجاز: {{flight.cargo}} کیلوگرم</p>
                            <p class="card-text mt-1 pt-1 mb-2 pb-1">مدل هواپیما:  {{flight.airplane_model}} </p>
                            <p class="card-text mt-1 pt-1 mb-2 pb-1">ترمینال :  {{flight.terminal}} </p>
                            <a href="{% url 'trip:home'%}" class="btn btn-outline-dark rounded-pill w-100">لیست سفرها</a>
                            
                        </div>
                        <div class="card-footer text-muted">
                            <span class="m-2 pl-5">آخرین بروزرسانی:  </span>
                            {{flight.jupdated}}
                        </div>
                    </div>
                    
                </div>
               
            </div>
            
 
           
        </div>
    </div>
</div>





































        <!-- Post Content-->
        <!-- <article class="mb-4 mt-5 pt-5">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <p>Never in all their history have men been able truly to conceive of the world as one: a single sphere, a globe, having the qualities of a globe, a round earth in which all the directions eventually meet, in which there is no center because every point, or none, is center — an equal earth which all men occupy as equals. The airman's earth, if free men make it, will be truly round: a globe in practice, not in theory.</p>
                        <p>Science cuts two ways, of course; its products can be used for both good and evil. But there's no turning back from science. The early warnings about technological dangers also come from science.</p>
                        <p>What was most significant about the lunar voyage was not that man set foot on the Moon but that they set eye on the earth.</p>
                        <p>A Chinese tale tells of some men sent to harm a young girl who, upon seeing her beauty, become her protectors rather than her violators. That's how I felt seeing the Earth for the first time. I could not help but love and cherish her.</p>
                        <p>For those who have seen the Earth from space, and for the hundreds and perhaps thousands more who will, the experience most certainly changes your perspective. The things that we share in our world are far more valuable than those which divide us.</p>
                        <h2 class="section-heading">The Final Frontier</h2>
                        <p>There can be no thought of finishing for ‘aiming for the stars.’ Both figuratively and literally, it is a task to occupy the generations. And no matter how much progress one makes, there is always the thrill of just beginning.</p>
                        <p>There can be no thought of finishing for ‘aiming for the stars.’ Both figuratively and literally, it is a task to occupy the generations. And no matter how much progress one makes, there is always the thrill of just beginning.</p>
                        <blockquote class="blockquote">The dreams of yesterday are the hopes of today and the reality of tomorrow. Science has not yet mastered prophecy. We predict too much for the next year and yet far too little for the next ten.</blockquote>
                        <p>Spaceflights cannot be stopped. This is not the work of any one man or even a group of men. It is a historical process which mankind is carrying out in accordance with the natural laws of human development.</p>
                        <h2 class="section-heading">Reaching for the Stars</h2>
                        <p>As we got further and further away, it [the Earth] diminished in size. Finally it shrank to the size of a marble, the most beautiful you can imagine. That beautiful, warm, living object looked so fragile, so delicate, that if you touched it with a finger it would crumble and fall apart. Seeing this has to change a man.</p>
                        <a href="#!"><img class="img-fluid" src="assets/img/post-sample-image.jpg" alt="..." /></a>
                        <span class="caption text-muted">To go places and do things that have never been done before – that’s what living is all about.</span>
                        <p>Space, the final frontier. These are the voyages of the Starship Enterprise. Its five-year mission: to explore strange new worlds, to seek out new life and new civilizations, to boldly go where no man has gone before.</p>
                        <p>As I stand out here in the wonders of the unknown at Hadley, I sort of realize there’s a fundamental truth to our nature, Man must explore, and this is exploration at its greatest.</p>
                        <p>
                            Placeholder text by
                            <a href="http://spaceipsum.com/">Space Ipsum</a>
                            &middot; Images by
                            <a href="https://www.flickr.com/photos/nasacommons/">NASA on The Commons</a>
                        </p>
                    </div>
                </div>
            </div>
        </article>
        
        -->
{%endblock%}

apiservices/templates/trip/flight_list.html
{%extends 'trip/base.html'%}
{% load static%}
{% block main %}
<div class="container px-4 px-lg-5 ">
    <div class="row gx-4 gx-lg-5 justify-content-center mt-5 pt-5">
        {% for hadis in object.sentence %}
        <div class="shadow p-3 mb-4 bg-body-tertiary rounded row gx-4 gx-lg-5 justify-content-center ">{{hadis.sentence}}</div>
        {%endfor%}
        
        <!-- col-md-1 col-lg-4 col-xl-4 d-inline-flex w-100  -->
        <div class="row row-cols-2 row-cols-md-3 row-cols-lg-4 g-1 w-100 d-inline-flex">
            
            <!-- <div class="card-columns mh-100 " > -->
        <!-- Post preview-->
        <!-- <div class="shadow-lg p-3 mb-5 bg-body-tertiary rounded row gx-4 gx-lg-5 justify-content-center "> -->
            {% for flight in object_list %}
            <div class = "m-0">
                    {% comment %} <p>نویسند: {{flight.author}}</p> {% endcomment %}


                    <div class=" card border-dark mb-3 rounded-3 shadow" >
                        <div class="card text-center d-inline">
                            {% for cat in flight.category_published.all %}

                            
                            <a href="{% url 'trip:category' cat.slug %} " class="btn btn-outline-info rounded-pill p-2 m-1"style= "font-size:10px">{{cat.title}}</a>
                              
                                                       
                            {% endfor %}
                        
                            
                        </div>
                        <div class="card-body pb-2">
                            <h5 class="card-title text-center"> {{flight.source}} <i class='far fas fa-arrow-left' style="font-size:12px;color:red" >	</i>  {{flight.destination}} </h5>
                            <div class = "d-inline-flex mt-1 pt-1">

                                <img src= '{{flight.thumbnail.url}}'class="img-fluid rounded" alt="{{flight.slug}}"style="width: 50px;height: 50px">
                                <small class = "m-3"> {{flight.company}}</small>
                            </div>
                            <p class="card-text mt-1 pt-1 mb-1 pb-1"style= "font-size:14px">تاریخ پرواز: {{flight.jdate}}</p>
                            <p class="card-text mt-1 pt-1 mb-2 pb-1"style= "font-size:14px">ساعت پرواز: {{flight.fly_time}}</p>
                            <a href="{% url 'trip:detail' flight.slug%}" class="btn btn-outline-dark rounded-pill w-100 p-1 "style="height: 25px;font-size:12px">جزییات</a>
                            
                        </div>
                        <div class="card-footer text-muted text-center pt-1" style= "font-size:12px">
                            {{flight.jupdated}}
                        </div>
                    </div>
                    
                </div>
                {%endfor%}
            </div>
            
        
        



            <!-- <div class="post-preview">
                {%for trip in trips%}
                <a href="post.html">
                    <h class="post-title">{{trip.title}}</h2>
                    <h5 class="post-subtitle">{{trip.explanation}}</h5>
                </a>
                <p class="post-meta">
                    Posted by
                    <a href="#!">{{trip.copyright}}</a>
                    on {{trip.date}}
                </p>
                <hr class="my-4" />
                    {%endfor%}
            </div> -->
            <!-- </div> -->
            <!-- Divider-->
            <!-- Post preview-->
           
            <!-- Divider-->
            <!-- <hr class="my-4" /> -->
            <!-- Pager-->
            {% if is_paginated%}
            <div class="d-flex justify-content-center mb-2 pager-bottom ">
                {% if page_obj.has_previous%}
                <a class="btn btn-outline-success text-uppercase rounded-pill m-2" href="{% url 'trip:home' page_obj.previous_page_number%}"><i class='fas fa-chevron-right' style='font-size:11px'></i>  لیست سفرهای جدید </a>
                {%endif%}
                {%if page_obj.has_next%}
                <a class="btn btn-outline-success text-uppercase rounded-pill m-2" href="{% url 'trip:home' page_obj.next_page_number %}">  لیست سفرهای قدیمی <i class='fas fa-chevron-left' style='font-size:11px'></i></a>
                {%endif%}
            </div>
            {%endif%}
    
        </div>
    </div>
</div>
{%endblock%}